### ISSUE TITLE
Colab notebook porting on TensorFlow 2

### ISSUE THREAD

**Issue by virtualramblas** [lukun199/TBEFN#2]
Hi,

Just to notify that an unofficial Colab notebook for TensorFlow 2 is available [here](https://github.com/virtualramblas/python-notebooks-repo/tree/main/Colab/TBEFN).

Best Regards,
Guglielmo

**Comment by lukun199** [comment]
Hi Guglielmo,
Thank you for helping this work run on tf 2.x! We would like to add your modifications here : )

**Comment by virtualramblas** [comment]
Hi Kun,

Thanks you for your feedback.
I could start a pull request later today to add the TF 2 script and the Colab notebook as well if needed.

Best Regards,
Guglielmo

**Comment by lukun199** [comment]
That would be of great help. Thank you.

**Comment by virtualramblas** [comment]
Pull Request submitted.

**Comment by lukun199** [comment]
Merged this PR!

**Comment by virtualramblas** [comment]
Thanks Kun :)
