### ISSUE TITLE
Convert to Pb Model

### ISSUE THREAD

**Issue by kundanSingh11** [lukun199/TBEFN#4]
Hi I was trying to convert it in .pb file but was unsuccessful can you tell me what is the input and output node name.

**Comment by lukun199** [comment]
I provide a demo in the newly uploaded folder `extension`. It shows how to convert the model into `.pb` format, and to verify it. These scripts are tested under tf 1.13.1 and 1.12.0. Please ref to the latest version :).
Personally I am not familiar as regard to use the model in cpp or other cases, and that's what I can do for you.

**Comment by kundanSingh11** [comment]
It worked.
Thank you for this great project and your help.
